name: flutter_widgets
description: This application is based on "Widget of the Week" from the Flutter Channel (YouTube)

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.5
  transparent_image: ^2.0.0
  google_mobile_ads: ^2.3.0
  url_launcher: ^6.1.7
  location: ^4.4.0
  geocoder2: ^1.4.0
  google_maps_flutter: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/aurora-borealis.jpg
    - assets/images/flutter-fade-in-image.jpg
    - assets/images/github_logo.png
    - assets/images/landscape.jpg
    - assets/images/loading.gif
