name: flutter_widgets
description: This application is based on "Widget of the Week" from the Flutter Channel (YouTube)

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  transparent_image: ^1.0.0
  google_mobile_ads: ^0.12.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/aurora-borealis.jpg
    - assets/images/flutter-fade-in-image.jpg
    - assets/images/github_logo.png
    - assets/images/landscape.jpg
    - assets/images/loading.gif
